evenbritedevise/config/routes.rb
Rails.application.routes.draw do
  get 'events/index', to:"events#index" 
  get 'events/show', to:"events#show" 
  get 'events/new', to:"events#new" 
  get "events/suscribe/:id", to: "events#suscribe", as: "event_suscription" 
  get 'users/index'
  get 'users/show'
  devise_for :users
  root 'users#index'

    post 'events/show'

resources :events
post "events/suscribe/:id", to: "events#suscribe", as: "event_s"
  
resources :charges, only: [:new, :create]

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

evenbritedevise/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

evenbritedevise/app/models/event.rb
class Event < ApplicationRecord

  belongs_to :creator, class_name: 'User'
  has_many :event_attendees
  has_many :attendees, through: :event_attendee
end

evenbritedevise/app/models/event_attendee.rb
class EventAttendee < ApplicationRecord
belongs_to :event 
belongs_to :attendee, class_name: 'User', foreign_key: :attendee_id
end

evenbritedevise/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

has_many :created_events, class_name: 'Event', foreign_key: :creator_id
has_many :event_attendees, foreign_key: 'attendee_id'
has_many :attending_events, through: :event_attendees, source:   :event
end


 

evenbritedevise/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

evenbritedevise/app/controllers/charges_controller.rb
class ChargesController < ApplicationController
	def new
	end

		def create
  # Amount in cents
  @amount = 500

  customer = Stripe::Customer.create(
    :email => params[:stripeEmail],
    :source  => params[:stripeToken]
  )

  charge = Stripe::Charge.create(
    :customer    => customer.id,
    :amount      => @amount,
    :description => 'Rails Stripe customer',
    :currency    => 'eur'
  )

rescue Stripe::CardError => e
  flash[:error] = e.message
  redirect_to new_charge_path
		end
end

evenbritedevise/app/controllers/events_controller.rb
class EventsController < ApplicationController
  

def create

	@event = Event.new
  	@event.date = params[:date]
		@event.description = params[:description]
		@event.place = params[:place]
		@event.creator_id = current_user.id
		@event.price = params[:price].to_f / 100
		@event.creator = current_user
  	if @event.save
  	flash[:success] = "Votre événement a bien été créé !"    
  		redirect_to @event
  	else render 'new'
  	end
  end

  def show
    @event = Event.find(params[:id])
  end

  def new
  	@event = Event.new
  end





  def suscribe
    @event = Event.find(params[:id])
    if 
    @event.event_attendees.include? current_user.id
    flash[:error] = "Tu participes déjà à l'événement !" 
    redirect_to @event
    else
    @event.event_attendees << current_user.id
    flash[:success] = "Tu participes à l'événement !" 
    redirect_to @event
    end

    private
  	def event_params
      params.permit(:price, :description, :date, :place)
  	end
  end
end

evenbritedevise/app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
  end

  def show
  end
end

evenbritedevise/app/helpers/application_helper.rb
module ApplicationHelper
end

evenbritedevise/app/helpers/charges_helper.rb
module ChargesHelper
end

evenbritedevise/app/helpers/events_helper.rb
module EventsHelper
end

evenbritedevise/app/helpers/users_helper.rb
module UsersHelper
end

evenbritedevise/app/views/charges/create.html.erb
<h2>Merci pour ta caution :)</h2>

evenbritedevise/app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount: $5.00</span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="500"
          data-locale="auto"></script>
<% end %>

evenbritedevise/app/views/events/index.html.erb
<h1>Events#index</h1>
<p>Find me in app/views/events/index.html.erb</p>

evenbritedevise/app/views/events/new.html.erb
<% if user_signed_in? %>
<h1>Créer votre évent !</h1>

<%= form_tag (events_path) do %>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    
  
  <p> <%= label_tag 'description', "Quel model recherche tu ? Un H, une F ou peu importe" %> </p>
  <p> <%= text_field_tag(:description, "Model Mixte cheveux mi-long") %> </p>

  <p> <%= label_tag 'place', "Dans quelle ville se déroule t-il ?" %> </p>
  <p> <%= text_field_tag(:place) %> </p>

  <p> <%= label_tag 'date', "Quand se déroule ta prestation ?" %> </p>
  <p> <%= date_field_tag(:date) %> </p>
  <p> <%= label_tag 'price', "Combien d'euros vas tu faire payer ta prestation si ton model te met un lapin ?" %> </p>
  <p> <%= number_field_tag(:price) %> </p>

  </div>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
<p> <%= submit_tag 'Je crée mon event', class: "btn btn-primary"%></p>

  </div>
</div>
<% end %>


<% else %>
<h1>Oh nooon !</h1> <h2> Vous n'êtes pas connécté </h2>
<h3>Veuillez vous connécter pour créer un event :)</h3>
          <li><%= link_to "Se connecter", new_user_session_path %></li>
        <% end %>   

evenbritedevise/app/views/events/show.html.erb
<% if user_signed_in? %>
            
                <h1>Récapitulatif </h1>
<h3>model recherché : <%= @event.description %> </h3>

<% if @event.price == 0 %>
<h3>Il n'y a pas de caution pour cet évènement</h3>
<% else %>
<h3> Pssit n'oublie pas ton rendez-vous GRATUIT, si tu ne viens pas comme convenu ta caution de : <%= @event.price %>€ sera facturée</h3>
<% end %>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <p> <%= @event.price %></p>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A month's subscription"
          data-amount="@event.price"
          data-locale="auto"></script>
<% end %>


        <% else %>

        <h1>Oh un inconnu !</h1>
        <h3>Merci de te connecter ou t'inscrire pour accéder à l'évènement</h3>
          
        <% end %>      
            

evenbritedevise/app/views/layouts/_header.html.erb
  <header>
      <nav class="navbar navbar-default navbar-inverse">
   <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Open Beauty</a>
    </div>

    
      
      <ul class="nav navbar-nav navbar-right">
      	<li><%= link_to "Obtenir une coiffure gratuite", root_path %></li>
      	<li><%= link_to "Créer un évènement", events_new_path %></li>
<% if user_signed_in? %>
            
                <%= link_to "Se déconnecter", destroy_user_session_path, method: :delete %>  %>
              </li>
               </ul>
          </li>
        <% else %>
          <li><%= link_to "S'inscrire", new_user_registration_path %></li>
          <li><%= link_to "Se connecter", new_user_session_path %></li>
        <% end %>      
            
        
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
 
		</nav>
    </header>  

evenbritedevise/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Evenbritedevise</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link href="assets/css/bootstrap-responsive.css" rel="stylesheet">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= favicon_link_tag 'noun_3169.png' %>
  </head>

  <body>
    
   <%= render 'layouts/header' %>
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>

  <% end %>
    <%= yield %>
  </body>
</html>

evenbritedevise/app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
  <head></head>
  <body>
    <%= yield %>
  </body>
</html>

evenbritedevise/app/views/users/index.html.erb
<h4>Obtiens une coupe de cheveux gratuite en t'inscrivant aux évènements près de chez toi et découvre ainsi les nouveaux talents du monde de la beauté.</h4>

<h3>Liste des sessions de coiffure gratuite</h3>
 
<table class="table table-striped">
  <tr>
    <th>Sexe / Genre</th>
    <th>Date</th>
    <th>Lieu</th>
    <th>Caution en cas d'annulation</th>
    <th></th>

  </tr>
 <%@events = Event.all %>
  <% @events.each do |event|%> 
  <% if event.date >= Date.today %>
    <tr>
      <td><%= event.description %></td>
      <td><%= event.date.strftime("%d-%m-%Y") %></td>
      <td><%= event.place %></td>
      <td><%= event.price %>€</td>
      <td><%= link_to "j'y vais", event_path(event) %></td>

    </tr>
  <% end %>
<% end %>

</table>

<h4> Evénements passés </h4>

<table class="table table-striped">
  <tr>
    <th>Sexe / Genre</th>
    <th>Date</th>
    <th>Lieu</th>
    <th>Caution en cas d'annulation</th>
    <th></th>

  </tr>
 
  <% @events.each do |event|%> 
  <% if event.date < Date.today %>
    <tr>
     <td><%= event.description %></td>
      <td><%= event.date.strftime("%d-%m-%Y") %></td>
      <td><%= event.place %></td>
      <td><%= event.price %>€</td>

      

    </tr>
  <% end %>
<% end %>

</table>

evenbritedevise/app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>